ER図の作成
sakasu04/Sukiyaki_encyclopedia pull request #4
Opened 2023-01-29 02:05 UTC by sakasu04

draw.ioにてER図の作成を行いました。
お手数おかけいたしますが、ご確認よろしくお願いします。

2023-01-29 07:31 UTC, takyyk commented
@sakasu04 
こちらテーブル設計図が見れなかったので、見れるようにスクリーンショット等で共有お願いします！
またカラム名の補足等もお願いできればと思います！

2023-01-29 14:49 UTC, sakasu04 commented
> @sakasu04 こちらテーブル設計図が見れなかったので、見れるようにスクリーンショット等で共有お願いします！ またカラム名の補足等もお願いできればと思います！
⇒失礼いたしました。本コメントにスクリーンショットを添付いたします。
またカラム名の補足は以下の通りです。

●Usersテーブル
アカウント登録(email/crypted_password/salt)用に加えて、
プロフィール用にプロフィール画像(profile_image_path)や好きなすき焼きの具材(favorite_ingredient)を追加しております。

●Ingredient_postsテーブル
具材投稿用のテーブルです。
具材画像(image_path)と具材の説明(body)カラムを用意しております。

●Ingredient_votesテーブル
具材投票の中間テーブルです。
カリキュラムで学んだlike機能と同様に中間テーブルを設けました。

●Recipesテーブル
すき焼きのテシピのテーブルです。
すき焼きの種類4種類(Sukiyaki_type)を選択し、
レシピの説明(recipe_explanation)、具材(ingredient)、作り方(procedure)を保存できるカラムを用意いたしました。

<img width="766" alt="スクリーンショット 2023-01-29 23 39 53" src="https://user-images.githubusercontent.com/90917750/215333811-1a3dd938-1f48-49a6-96a3-f2c680aa6511.png">

2023-01-29 21:57 UTC, busitora commented
- テーブル名、表記は _Users_ にするなら _Ingredient_posts_ にするなど、統一してください
- Sukiyaki_type のS は なぜ大文字なのでしょうか？

2023-01-29 23:57 UTC, sakasu04 commented
ご指摘ありがとうございます。
ご指摘を受けて修正したER図のスリーんショットを添付いたします。

また下記コメントに修正した点を記載しております。
ご確認よろしくお願いいたします。

> * テーブル名、表記は _Users_ にするなら _Ingredient_posts_ にするなど、統一してください
⇒テーブル名すべて複数形にできているはずです。。再度ご確認いただけますと幸いです。
> * Sukiyaki_type のS は なぜ大文字なのでしょうか？
⇒大変失礼いたしました。こちらのミスです。小文字に修正しました。
> * path より url の方が一般的かもしれないですね
⇒ありがとうございます。pathをurlに変更しました。

![スクリーンショット 2023-01-30 8 54 06](https://user-images.githubusercontent.com/90917750/215363463-2327ced0-88f5-4c15-ba91-935c11b838c9.png)

2023-01-30 10:17 UTC, busitora requested changes
LGTM！！！

2023-01-30 10:17 UTC, busitora approved these changes
LGTM！

2023-02-05 07:11 UTC, merged